name: Backend CD Pipeline

on:
  workflow_run:
    workflows: ['Backend CI Pipeline']
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H root@92.112.180.180 >> ~/.ssh/known_hosts

      - name: Docker - Prune Server
        run: |
          echo "Pruning Docker system to remove unused containers, networks, images, and volumes..."
          sudo docker system prune -a --volumes -f

      - name: Stop and Remove Old Docker Container
        run: |
          CONTAINER_ID=$(sudo docker ps -a -q -f name=poultrypal-backend-container)
          if [ -n "$CONTAINER_ID" ]; then
            echo "Stopping and removing old container..."
            sudo docker stop "$CONTAINER_ID"
            sudo docker rm -f "$CONTAINER_ID"
          else
            echo "No old container to remove."
          fi

      - name: Delete Docker Image with Tag latest
        run: |
          IMAGE_ID=$(sudo docker images -q kalibbalajohnson/poultrypal-backend:latest)
          if [ -n "$IMAGE_ID" ]; then
            echo "Deleting Docker image with tag latest..."
            sudo docker rmi -f "$IMAGE_ID"
          else
            echo "No image with tag latest to remove."
          fi

      - name: Pull Docker Image
        run: sudo docker pull kalibbalajohnson/poultrypal-backend:latest

      - name: Run Docker Container
        run: |
          sudo docker run -d -p 3000:3000 --name poultrypal-backend-container kalibbalajohnson/poultrypal-backend:latest