name: Model CD Pipeline

on:
  workflow_run:
    workflows: ['Model CI Pipeline']
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 92.112.180.180 >> ~/.ssh/known_hosts

      - name: Deploy to Server via SSH
        run: |
          ssh root@92.112.180.180 << 'EOF'
          echo "SSH connection successful."
          docker ps

          echo "Pruning Docker system to remove unused containers, networks, images, and volumes..."
          docker system prune -a --volumes -f

          echo "Stopping and removing old container..."
          CONTAINER_ID=$(docker ps -a -q -f name=poultrypal-model-container)
          if [ -n "$CONTAINER_ID" ]; then
            docker stop "$CONTAINER_ID"
            docker rm -f "$CONTAINER_ID"
          else
            echo "No old container to remove."
          fi

          echo "Deleting Docker image with tag latest..."
          IMAGE_ID=$(docker images -q kalibbalajohnson/poultrypal-model:latest)
          if [ -n "$IMAGE_ID" ]; then
            docker rmi -f "$IMAGE_ID"
          else
            echo "No image with tag latest to remove."
          fi

          echo "Pulling new Docker image..."
          docker pull kalibbalajohnson/poultrypal-model:latest

          echo "Running new Docker container..."
          docker run -d -p 8000:8000 --name poultrypal-model-container kalibbalajohnson/poultrypal-model:latest
          docker ps
          EOF