name: CD Pipeline

on:
  workflow_run:
    workflows: ['CI Pipeline']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Docker - Prune Server
        run: |
          echo "Pruning Docker system to remove unused containers, networks, images, and volumes..."
          sudo docker system prune -a --volumes -f

      - name: Stop and Remove Old Docker Container
        run: |
          CONTAINER_ID=$(sudo docker ps -a -q -f name=poultrypal-container)
          if [ -n "$CONTAINER_ID" ]; then
            echo "Stopping and removing old container..."
            sudo docker stop "$CONTAINER_ID"
            sudo docker rm -f "$CONTAINER_ID"
          else
            echo "No old container to remove."
          fi

      - name: Delete Docker Image with Tag latest
        run: |
          IMAGE_ID=$(sudo docker images -q kalibbalajohnson/poultrypal:latest)
          if [ -n "$IMAGE_ID" ]; then
            echo "Deleting Docker image with tag latest..."
            sudo docker rmi -f "$IMAGE_ID"
          else
            echo "No image with tag latest to remove."
          fi

      - name: Pull Docker Image
        run: sudo docker pull kalibbalajohnson/poultrypal:latest

      - name: Run Docker Container
        run: |
          sudo docker run -d -p 5137:5137 --name poultrypal-container kalibbalajohnson/poultrypal:latest