name: Model CI Pipeline

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: cd AI-Model && docker build -t kalibbalajohnson/poultrypal-model .

      - name: Add latest tag to image
        run: docker tag kalibbalajohnson/poultrypal-model kalibbalajohnson/poultrypal-model:latest

      - name: Push to Dockerhub
        run: docker push kalibbalajohnson/poultrypal-model:latest